[site]
title = "LEWIS WANG"
description = "MSc Accounting and Analytics at Trinity College Dublin."
favicon = "/favicon.svg"
last_updated = "11 MAY, 2026"

[author]
name = "Zhenyuan Zhang"
title = "PhD Student"
institution = "Liverpool John Moores University, UK"
avatar = "/IMG_2649.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "lewisww09@gmail.com"
location = "Dublin, Ireland"
# location_url = "https://maps.google.com"
location_details = [
  "Dublin, Ireland",
]
google_scholar = "https://scholar.google.com/citations?user=u2bn2HsAAAAJ&hl=en"
# orcid = "https://orcid.org"
github = "https://github.com/lewis09-dotcom.github.io"
linkedin = "http://linkedin.com/in/lewiswang0927"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

# [[navigation]]
# title = "Teaching"
# type = "page"
# target = "teaching"
# href = "/teaching"

# [[navigation]]
# title = "Awards"
# type = "page"
# target = "awards"
# href = "/awards"

[[navigation]]
title = "Experiences"
type = "page"
target = "experiences"
href = "/experiences"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
